name: book_app
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - res/Ceuxquivousquittent.jpg 
    - res/Croissance.jpg 
    - res/Dites-leur.jpg 
    - res/FaitsCle.jpg 
    - res/Recevoir.jpg    